config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'about' => 'welome#about'
  get '/home' => 'welcome#home'

  resources :problems do
    collection do
      get :today
      get :step1 
      get :step2
      get :step3
      get :calender
      get :aboutus
    end
  end

  devise_for :users
  resources :users, only: [] do
    collection do
      get :setting
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
  validates_presence_of :content, :user_id

  belongs_to :user

  enum category: { fear: 0, worry: 1 }

  scope :by_step, -> (step) do
    if step == 4
      where.not(solution: nil)
    elsif step == 3
      where(solution: nil).where.not(due_date: nil)
    elsif step == 2
      where(solution: nil, due_date: nil).where.not(category: nil)
    else
      where(solution: nil, due_date: nil, category: nil)
    end
  end

  def step
    if solution.present?
      4
    elsif due_date.present?
      3
    elsif category.present?
      2
    else
      1
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	before_action :authenticate_user!

	def index
		@problems = Problem.all
	end

	def new	
	end

	def create
		@problem = Problem.new(problem_params)
		@problem.save

		respond_to do |format|
			format.js
		end
	end

	def show
		@problem = Problem.all
	end
	def edit
	end

	def update
	end

	def today
	end

	def step1
		@problem = Problem.new
		@problems = Problem.all
	end

	def step2
	end
	def step3
	end

	def calender
	end
	
	def aboutus
	end
	def settings
	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def problem_params
    params.require(:problem).permit(:text)
  end  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    super do |resource|
      BackgroundWorker.trigger(resource)
    end
  end
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	  def index
		  if user_signed_in?
		    redirect_to today_problems_path
		  else
		    redirect_to home_path
		  end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FEWORRY!", home_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= "#{"active" if current_page?(today_problems_path)}" %>"><a href="/problems/today">Today<span class="sr-only">(current)</span></a></li>
        <li class="<%= "#{"active" if current_page?(step1_problems_path)}" %>"><a href="/problems/step1">New<span class="sr-only">(current)</span></a></li>
         <li class="<%= "#{"active" if current_page?(calender_problems_path)}" %>"><a href="/problems/calender">Calendar<span class="sr-only">(current)</span></a></li>
            
          </ul>
        </li>
      </ul>
      
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to('About us', aboutus_problems_path) %></li>
            <li><%=link_to('Settigns')%></li>
            
          </ul>
        </li>
            
          </ul>
        </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapstoneJ</title>
    <%= csrf_meta_tags %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />


  </head>

  <body>
    <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%=render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/problems/_index.html.erb
<div class="prob-before">
	<p>
		<% @problems.each do |problem| %>
			<tr>
				<td><%= problem.text %></td>
				<td><%= link_to 'Show', Problem_path(problem) %></td>
			</tr>
		<% end %>
	</p>
</div>

app/views/problems/aboutus.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<h1>About Us</h1>
		<h2>Team Valuelab</h2>
	</body>
</html>

app/views/problems/calender.html.erb
	<head>
	<style>
	ul {list-style-type: none;}
body {font-family: Verdana, sans-serif;}

/* Month header */
.month {
    padding: 70px 25px;
    width: 100%;
    background: #1abc9c;
}

/* Month list */
.month ul {
    margin: 0;
    padding: 0;
}

.month ul li {
    color: white;
    font-size: 20px;
    text-transform: uppercase;
    letter-spacing: 3px;
}

/* Previous button inside month header */
.month .prev {
    float: left;
    padding-top: 10px;
}

/* Next button */
.month .next {
    float: right;
    padding-top: 10px;
}

/* Weekdays (Mon-Sun) */
.weekdays {
    margin: 0;
    padding: 10px 0;
    background-color:#ddd;
}

.weekdays li {
    display: inline-block;
    width: 13.6%;
    color: #666;
    text-align: center;
}

/* Days (1-31) */
.days {
    padding: 10px 0;
    background: #eee;
    margin: 0;
}

.days li {
    list-style-type: none;
    display: inline-block;
    width: 13.6%;
    text-align: center;
    margin-bottom: 5px;
    font-size:12px;
    color:#777;
}

/* Highlight the "current" day */
.days li .active {
    padding: 5px;
    background: #1abc9c;
    color: white !important
	</style>
	
	</head>
	<body>
		<h1>calendar</h1>
		 <div class="month">
			  <ul>
			    <li class="prev">&#10094;</li>
			    <li class="next">&#10095;</li>
			    <li>
			      November<br>
			      <span style="font-size:18px">2016</span>
			    </li>
			  </ul>
			</div>

			<ul class="weekdays">
			  <li>Mo</li>
			  <li>Tu</li>
			  <li>We</li>
			  <li>Th</li>
			  <li>Fr</li>
			  <li>Sa</li>
			  <li>Su</li>
			</ul>

			<ul class="days">
			<li></li>
			<li></li>
			  <li>1</li>
			  <li>2</li>
			  <li>3</li>
			  <li>4</li>
			  <li>5</li>
			  <li>6</li>
			  <li>7</li>
			  <li>8</li>
			  <li>9</li>
			  <li><span class="active">10</span></li>
			  <li>11</li>
			  <li>12</li>
			  <li>13</li>
			  <li>14</li>
			  <li>15</li>
			  <li>16</li>
			  <li>17</li>
			  <li>18</li>
			  <li>19</li>
			  <li>20</li>
			  <li>21</li>
			  <li>22</li>
			  <li>23</li>
			  <li>24</li>
			  <li>25</li>
			  <li>26</li>
			  <li>27</li>
			  <li>28</li>
			  <li>29</li>
			  <li>30</li>
			  <li>31</li>

			</ul>
	</body>

app/views/problems/index.html.erb
<%= render 'index' %>

app/views/problems/newstep.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<div class="container">
			<div class="description">
				<h1>Step1.</h1>
				<h2>Fill the form below with your concern whatever it is.</h2>

				<h2>Then Hit the "Add" button</h2>

				<h2>If you added all, Hit "Create Problem"  </h2>
			</div>

			<div class="form">
			<%= form_for(@problem) do |f| %>
			  <p>
			    <%= f.label :content %><br>
			    <%= f.text_area :content, size: "50x10" %>
			  </p>
			 
			  <p>
			    <%= f.submit %>
			  </p>
			  <% end %>
			
		</div>	
			<%= render 'index' %>

			<div class="next" align : right>
				<button type="button" class="btn">Next</button>
			</div>
	</body>
</html>

app/views/problems/step1.html.erb
<div class="container">
	<div class="description">
		<h1>Step1.</h1>
		<h2>Fill the form below with your concern whatever it is.</h2>

		<h2>Then Hit the "Add" button</h2>

		<h2>If you added all, Hit "Create Problem"  </h2>
	</div>

	<div class="form">
		<%= form_for(@problem) do |f| %>
			<p>
			<%= f.label :content %><br>
			<%= f.text_area :content, size: "50x10" %>
			</p>

			<p>
			<%= f.submit %>
			</p>
		<% end %>
	</div>



	<%= render 'index' %>
	<%= link_to "Next" , step2_problems_path, class: "btn" %>	
</div>

app/views/problems/step2.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<div class="container">
			<div class="description">
			<h1>Step 2</h1>
			<h2>Devide them into 2 groups, worry and fear</h2>
			<h2>We will destroy all the fears later</h2>
			<h2> You're done, hit the 'Next'!</h2>
			<h4>Notice: worry is real problem part and fear is just feeling or unrealistic concerns of future</h4>
			
			</div>

			<div class="prob-before">

			<div class="list">

			</div>

			<div class="next">
			<%= link_to "Next", step3_problems_path,  class: "btn" %>

		</div>

	</body>
</html>


<!-- 
#checkbox form
<label class="checkbox-inline">
  <input type="checkbox" id="inlineCheckbox1" value="option1"> Worry
</label>
<label class="checkbox-inline">
  <input type="checkbox" id="inlineCheckbox2" value="option2"> Fear
</label>

##button form 
# blue
<button type="button" class="btn btn-primary">Primary</button>
# red
<button type="button" class="btn btn-danger">Danger</button>
-->

app/views/problems/step3.html.erb
	<head>

	</head>
	<body>
		<div class="container">
			<div class="description">
				<h1>Step 3. Let's set the due-date to make answers of problems!</h1>
				<h2>If you click 'now' You have to write the solution right now</h2>
				<h2>If you click 'After' You can set the due-date</h2>
				
			<div class="list" style="padding:50px">
			<h4>I have to decide whether to apply for intership of Asan</h4>

				<button type="button" class="btn">Now</button>
				<button type="button" class="btn">After</button>
				<br>
			<h4>My friend scolded me about what I didn't do</h4>

				<button type="button" class="btn">Now</button>
				<button type="button" class="btn">After</button>
				<br>
			<h4>I have to find my old images for my projects</h4>

				<button type="button" class="btn">Now</button>
				<button type="button" class="btn">After</button>
				<br>			
			<h4>I have to submit my cover letter for my job</h4>

				<button type="button" class="btn">Now</button>
				<button type="button" class="btn">After</button>
				<br>
			</div>

		</div>


			<%= link_to 'Finish',today_problems_path, class: "btn" %>

				
	</body>

app/views/problems/today.html.erb
	<head>
	</head>
	<body>
		<div class="list"; agign="center" ; style="padding:100px ; padding-left:500px">
		<h1 style="font-size: 50px">Today's problems</h1>
		<br>
		<br>
		<br>
		<div class="bflist" style="padding-top:100px">
		<h1 style="font-size: 50px"; align="center"; style="padding:100px; padding-left:500px">Today's problem(without solution)</h1>
		<br>
		<br>
		<br>

	</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/home.html.erb
<head>
<link rel=”stylesheet” type=”text/css” href="welcome.scss">
	<title>Feworry</title>
</head>
<body>

	<div class="container">
		<br>
		<h1  font-family="Arial" ; align="center";></h1>
		<br>
		<br>
		<br>
		<div class="contents" ; align="center">
			<div class="row">
			<br>
			<h2>When you have a lot of concerns in your mind,</h2>
			<br>
			<h2>You think you are getting trouble to make order of your problems</h2>
			<br>
			<br>
			<h2>I stronglly recommend you to use this app</h2>
			<br>
			<br>
			<h1 style="font-size: 100px">Feworry!</h1>
			
			<br>
			<br>
					<img src="http://postfiles1.naver.net/MjAxNjExMjJfMTQx/MDAxNDc5ODIyNjMwMDQ2.hT_9pkLJsg4U3XeXok8TGiRaMd2dtuLEKCW00btkIcYg.E8ys25L463wsqDxhjiocLBvqiqNV61huvuvhQr4jOPIg.PNG.lim_jiin/20161122_224533.png?type=w2" class="img1"img-responsive" style= "padding: 250px"">
		</div>	
			<br>
			<br>
			<h2>Feworry means </h2>
			<h2>Fear+Worry</h2>
			<br>
			<br>
			<h2>So, How does <p style= color: orange;>Feworry</p> controls our problems?</h2>
			<br>
			<br>
			<br>
			<br>
		</div>
			</div>
			<div class="row"; align="center";  background_color= "lightblue">
				<div class ="col-sm-4">
				<h1>Step 1</h1>
				<h2>Fisrt, You write your problems all.</h2>
				<img src="http://postfiles3.naver.net/MjAxNjExMTZfMTE5/MDAxNDc5Mjc2MTY4OTc4.MN_z-OgGcVXLHcL1qZlK2T0s0IT7PWEEYZho1ET9g0Ig.62_KESvBkaDeoT_gAB7UCINolwXMr17OfsjsZyZW9hEg.JPEG.lim_jiin/3._new1.jpg?type=w2" class="img-responsive" style= "padding-top:140px">

				</div>
				<div class ="col-sm-4">
				<h1>Step 2</h1>
				<h2>Devide them into 2 groups, worry and fear</h2>
				<h2>We will destroy all the fears later</h2>
				<h4>Notice: worry is real problem part and fear is just feeling or unrealistic concerns of future</h4>
				<img src="http://postfiles8.naver.net/MjAxNjExMTZfMTQ5/MDAxNDc5Mjc2MTcwMDM4.U6Ok2aa4SHvsRPh89Om0RlBeE1tBcjW5cl0rqCaDH_Ag.PmWfMIXcFWqmPK8FU428CHBm_hYdrgbcqqVExQMAYJ8g.JPEG.lim_jiin/5._new_2-2.jpg?type=w2" class="img-responsive" style= "padding-top:30px">
			
			     <br>
			     </div>
				<div class ="col-sm-4" ; border="5px";>
				<h1>Step 3</h1>
				<h2>And then, set the date "when" you will consider them!<br> If you can get any solution of the problem, write it right a way!</h2>
				<img src="http://postfiles8.naver.net/MjAxNjExMTZfMTYx/MDAxNDc5Mjc2MTcwNTYx.fqusjKY9llaxd5PDVpYiaFsFt6ocku6dhMGc7iXCnH0g.XNeeJsvG1v4r6IF_984elcXa4dv64upTGs5b5e5NPqMg.JPEG.lim_jiin/6._new3.jpg?type=w2" class="img-responsive" style= "padding-top:30px">
				<br>
				<br>
				<br>
				<br>
				</div>
			</div>

		<div class="row" >
	 		<div class="col-sm-12" ; align= "center">
		
				<%= link_to 'Start Right Now',today_problems_path, class: "btn btn-primary btn-lg" %>
			</div>
		</div>
	<br>
	<br>
	<br>
	
	<div class="footer" style="border-top: 50px">
		<h4 align="center">&copy;Copyright 2016 Jiin Lim</h4>

	</div> 
</body>

app/views/welcome/index.html.erb
<!DOCTYPE html>

<html>
<head>
<link rel=”stylesheet” type=”text/css” href="welcome.scss">
	<title>Feworry</title>
</head>
<body>

	<div class="container">
		<h1  style= "background-color:yellow" ; align="center">Welcome to Feworry!</h1>
		<br>
		<br>
		<div class="contents" ; align="center">
			<div class="row">
			<br>
			<h2>When you have a lot of concerns in your mind,</h2>
			<br>
			<h2>You think you are getting trouble to make order of your problems</h2>
			<br>
			<br>
			<h2>I stronglly recommend you to use this app</h2>
			<h1 style="font-size: 50px">Feworry!</h1>
			<br>
			<h2>Feworry means </h2>
			<h2>Fear+Worry</h2>
			<br>
			<br>
			<h2>So, How does <p style= color: orange;>Feworry</p> controls our problems?</h2>
			<br>
			<br>
			<br>
			<br>
		</div>
			</div>
			<div class="row", align="center"; >
				<div class ="col-sm-4">
				<h1>Step 1</h1>
				<h2>Fisrt, You write your problems all.</h2>
				
				</div>
				<div class ="col-sm-4">
				<h1>Step 2</h1>
				<h2>Devide them into 2 groups, worry and fear</h2>
				<h2>We will destroy all the fears later</h2>
				<h4>Notice: worry is real problem part and fear is just feeling or unrealistic concerns of future</h4>
			     <br>
			     </div>
				<div class ="col-sm-4">
				<h1>Step 3</h1>
				<h2>And then, set the date "when" you will consider them!<br> If you can get any solution of the problem, write it right a way!</h2>
				<br>
				<br>
				<h3>So now you don't have to think about all the problems 
				<br>because you put the problems rest off!</h3>
				<br>
				<br>
				</div>
			</div>

		<div class="row">
	 		<div class="col-sm-12" float="center">
		
				<%= link_to 'Start Right Now',today_path, class: "btn btn-primary btn-lg" %>
				<%= 'Tutorial' %>
			</div>
		</div>
	<br>
	<br>
	<br>
	
	<div class="footer">
		<id copy>copyright&cTeamJS</h2>
		<id contact>contact</h2>

	</div> 
</body>
</html>